name: HawkScan

on:
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Scan
    runs-on: ubuntu-latest
    env:
      COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
      BRANCH_NAME: ${{ github.head_ref }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm test
      - name: Run Vuln Node Express
        run: npm run start &
      - name: Run HawkScan
        env:
          HAWK_ENV: GitHub Actions
        continue-on-error: true
        uses: stackhawk/hawkscan-action@v1.3.4
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
          codeScanningAlerts: true
          githubToken: ${{ github.token }}
